#!/bin/bash
case "$1" in
	"")
echo "Script usage:"
echo "-c|--create Login Password ProjectID DoaminName ProjectName NetworkName PublicKey PrivateKey RouterIP Orchestrator Branch  - creating new instace "
echo "Orchestrator could be set to openstack or kubernetes "
echo "Branch parameter is optional"
echo "-d|--destroy Login Password ProjectID domainName ProjectName Orchestrator	- destroying instance"
;;
    --create|-c)


if [ -z "${12}" ]
  then
terraform apply -auto-approve -state-out="$2" -var='user_name='"$2" -var='password='"$3" -var='project_id='"$4" -var='domain_name='"$5" -var='project_name='"$6" \
-var='network_name='"$7" -var='ssh_key_file='"$8" -var='ssh_private_key='"$9" -var='routerip='"${10}" -var='flavor='"${13}" -var='contrailType='"${14}" ./"${11}"/
else
terraform apply -auto-approve -state-out="$2" -var='user_name='"$2" -var='password='"$3" -var='project_id='"$4" -var='domain_name='"$5" -var='project_name='"$6" \
-var='network_name='"$7" -var='ssh_key_file='"$8" -var='ssh_private_key='"$9" -var='routerip='"${10}" -var='branch='"${12}" -var='flavor='"${13}" -var='contrailType='"${14}" ./"${11}"/
fi
;;
    --destroy|-d)
terraform destroy -auto-approve -state="$2" -var='user_name='"$2" -var='password='"$3" -var='project_id='"$4" -var='domain_name='"$5" -var='project_name='"$6"  ./"${7}"/
;;
    *)
;;
esac
