#!/bin/bash

LocalIP=$1
RouterIP=$2
PublicIP=$3

TemplateFile="../../$4/$5/$6/template.yaml"
InstancesFile="../../$4/$5/$6/instances.yaml"

cp "$TemplateFile" "$InstancesFile"
sed  -i "s|@localip|$LocalIP|g" "$InstancesFile"
sed  -i "s|@routerip|$RouterIP|g" "$InstancesFile"
sed  -i "s|@publicip|$PublicIP|g" "$InstancesFile"
