#!/bin/bash

LocalIP=$1
PublicIP=$2
RouterIP=$3

InstancesFile="$4/instances.yaml"

sed -i "s|@localip|$LocalIP|g" "$InstancesFile"
sed -i "s|@publicip|$PublicIP|g" "$InstancesFile"
sed -i "s|@routerip|$RouterIP|g" "$InstancesFile"
